# Generated by Django 5.2.5 on 2025-11-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('title', models.CharField(max_length=30)),
                ('time', models.CharField(max_length=30)),
                ('artist', models.CharField(max_length=50)),
            ],
        ),
    ]
