# Generated by Django 5.2.5 on 2025-12-06 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlideImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slides/', verbose_name='スライド画像')),
                ('order', models.IntegerField(default=0, help_text='小さい数字ほど先に表示されます', verbose_name='表示順')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
