# Generated by Django 5.2.5 on 2025-12-16 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input_page', '0002_slideimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='artist',
        ),
        migrations.AddField(
            model_name='schedule',
            name='artist1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='artist2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='artist3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='artist4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
