# Generated by Django 5.2.5 on 2025-12-18 23:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input_page', '0003_remove_schedule_artist_schedule_artist1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog_photos/', verbose_name='投稿画像')),
                ('post_date', models.DateField(default=django.utils.timezone.now, verbose_name='投稿日')),
                ('description', models.TextField(max_length=500, verbose_name='説明文')),
            ],
            options={
                'verbose_name': 'ブログ投稿',
                'verbose_name_plural': 'ブログ投稿一覧',
                'ordering': ['-post_date'],
            },
        ),
    ]
