# Generated by Django 5.2.5 on 2025-12-20 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('input_page', '0004_blog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-id'], 'verbose_name': 'ブログ投稿', 'verbose_name_plural': 'ブログ投稿一覧'},
        ),
    ]
