# Generated by Django 5.2.5 on 2026-03-01 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input_page', '0005_alter_blog_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=255)),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'アクセスログ',
            },
        ),
    ]
