# Generated by Django 5.2.5 on 2026-03-23 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input_page', '0006_accesslog'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeLive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(help_text='youtu.be/XXXXX の XXXXX 部分', max_length=20, verbose_name='YouTube Video ID')),
                ('label', models.CharField(blank=True, max_length=100, verbose_name='ラベル（管理用メモ）')),
                ('is_active', models.BooleanField(default=True, verbose_name='表示する')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'YouTube ライブ',
                'verbose_name_plural': 'YouTube ライブ一覧',
            },
        ),
    ]
