# Generated by Django 5.2.5 on 2026-06-27 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input_page', '0007_youtubelive'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='seminar',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
