# Generated by Django 5.2.5 on 2026-06-27 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input_page', '0008_schedule_seminar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='seminar',
            field=models.BooleanField(default=False),
        ),
    ]
