# Generated by Django 5.2.5 on 2026-06-27 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input_page', '0009_alter_schedule_seminar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='time',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='title',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
